"use client";
import {useEffect,useState} from "react";

export default function GrabPool(){
 const [trips,setTrips]=useState([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[driverName,setDriverName]=useState(""),[driverPhone,setDriverPhone]=useState("");
 useEffect(()=>{try{setDriverName(localStorage.getItem("gd_driver_name")||"");setDriverPhone(localStorage.getItem("gd_driver_phone")||"")}catch{}},[]);
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/grab-pool",{cache:"no-store"});const j=await r.json();setTrips(j.trips||[])}catch{setMsg("目前無法讀取抓單池")}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
 const claim=async t=>{if(!driverName.trim())return setMsg("請先填司機姓名");try{localStorage.setItem("gd_driver_name",driverName.trim());localStorage.setItem("gd_driver_phone",driverPhone.trim())}catch{}if(!confirm(`確定接下 ${t.date||""} ${t.time||""} 這一趟？接單後會立即鎖單。`))return;setMsg("接單中…");try{const r=await fetch("/api/grab-pool",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tripId:t.id,driverName:driverName.trim(),driverPhone:driverPhone.trim()})});const j=await r.json();if(r.ok){setMsg("✅ 接單成功，車趟已鎖定並回傳主後台");setTrips(x=>x.filter(v=>v.id!==t.id))}else if(r.status===401)setMsg("請先登入 GD Car 帳號後再接單");else if(r.status===409){setMsg("這一趟已被其他司機接走");load()}else setMsg("接單失敗，請稍後再試")}catch{setMsg("網路異常，請稍後再試")}};
 return <main style={{maxWidth:760,margin:"0 auto",padding:"18px 14px 100px",fontFamily:"system-ui,-apple-system,sans-serif",background:"#f7f8f5",minHeight:"100vh",boxSizing:"border-box"}}><header style={{background:"#fff",borderRadius:18,padding:18,boxShadow:"0 2px 12px #00000010",marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><div style={{fontSize:12,color:"#657068",fontWeight:700}}>GD CAR DRIVER</div><a href="/grab/driver/my-trips" style={{fontSize:14,color:"#1f4a37",fontWeight:800}}>我的車趟 →</a></div><h1 style={{margin:"4px 0 6px",fontSize:26}}>🚐 司機接單大廳</h1><div style={{fontSize:13,color:"#657068"}}>只顯示後台已發布的車趟。第一位成功接單的司機會立即鎖單。</div><div style={{marginTop:10,padding:"9px 11px",background:"#f4f7f4",borderRadius:10,fontSize:12,color:"#536057"}}>🔒 接單前不顯示客戶姓名、電話與完整地址；成功接單後由主後台進行後續派車管理。</div></header>
 <section style={{background:"#fff",borderRadius:16,padding:14,marginBottom:12}}><b>我的接單資料</b><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:10}}><input value={driverName} onChange={e=>setDriverName(e.target.value)} placeholder="司機姓名＊" style={inp}/><input value={driverPhone} onChange={e=>setDriverPhone(e.target.value)} placeholder="聯絡電話" inputMode="tel" style={inp}/></div>{msg&&<div style={{marginTop:10,fontWeight:700,fontSize:14}}>{msg}</div>}</section>
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",margin:"14px 2px 8px"}}><b>可接車趟 {trips.length} 趟</b><button onClick={load} style={small}>重新整理</button></div>
 {loading&&trips.length===0?<div style={empty}>讀取中…</div>:trips.length===0?<div style={empty}>目前沒有公開車趟</div>:trips.map(t=><article key={t.id} style={{background:"#fff",borderRadius:16,padding:16,marginBottom:10,boxShadow:"0 1px 8px #0000000d"}}><div style={{fontWeight:800,fontSize:18}}>{t.date||"日期未定"}　{t.time||""}</div><div style={{marginTop:8,lineHeight:1.8}}>服務：{t.service||"-"}<br/>地區：{t.region||"-"}　航點：{t.airport||"-"}<br/>車型：{t.carClass||"-"}　行李：{t.luggage||"-"}　手提：{t.carryOn||"-"}{Number(t.childSeat)>0?<><br/>安全座椅：{t.childSeat}</>:null}{Number(t.booster)>0?<>　增高墊：{t.booster}</>:null}</div><div style={{fontSize:22,fontWeight:900,margin:"10px 0"}}>$ {Number(String(t.amount||0).replace(/,/g,"")).toLocaleString()}</div><button onClick={()=>claim(t)} style={{width:"100%",border:0,borderRadius:12,padding:"13px 16px",background:"#1f4a37",color:"white",fontWeight:800,fontSize:16}}>我要接單</button></article>)}
 </main>
}
const inp={width:"100%",boxSizing:"border-box",padding:"11px 12px",border:"1px solid #d9dfda",borderRadius:10,fontSize:15};
const small={border:"1px solid #cfd8d1",background:"white",borderRadius:10,padding:"7px 10px",fontWeight:700};
const empty={background:"#fff",borderRadius:16,padding:30,textAlign:"center",color:"#657068"};
