"use client";
import {useEffect,useState} from "react";
const empty={date:"",time:"",name:"",phone:"",pickup:"",dropoff:"",flight:"",passengers:"",luggage:"",carryOn:"",vehicle:"",amount:"",notes:"",driver:"",driverPhone:"",payment:"未收",returnMoney:"待回金",returnAccount:"",region:"",carClass:"",service:"機場接送",childSeat:"0",booster:"0",airport:"",extraStops:"",extraKm:"",crossCounty:"否"};
const sizes=["32吋","30吋","28吋","26吋","24吋","22吋","20吋","胖胖箱"];
const clean=(v="")=>v.replace(/^[：:\s]+|\s+$/g,"").trim();
function match(t,rs){for(const r of rs){const m=t.match(r);if(m?.[1])return clean(m[1])}return ""}
function parseDriver(text){const t=text.replace(/：/g,":");return {name:match(t,[/(?:司機|姓名)[:\s]*([^\n]+)/]),phone:match(t,[/(?:電話|手機)[:\s]*([^\n]+)/,/(09\d{2}[- ]?\d{3}[- ]?\d{3})/]),car:match(t,[/(?:車牌|車號|車型)[:\s]*([^\n]+)/]),license:/駕照.{0,5}(?:有|是|✓|已)/.test(t)?"是":"否",registration:/行照.{0,5}(?:有|是|✓|已)/.test(t)?"是":"否",insurance:/保險.{0,5}(?:有|是|✓|已)/.test(t)?"是":"否",blacklist:/黑名單.{0,5}(?:是|有|✓)/.test(t)?"是":"否"}}
function parseTrip(text){
 const raw=text.replace(/：/g,":").replace(/\r/g,""),lines=raw.split(/\n+/).map(x=>x.trim()).filter(Boolean),t=lines.join("\n"),o={...empty};
 const val=(labels)=>{for(const line of lines){for(const label of labels){const re=new RegExp("^\\s*"+label+"\\s*[:：]?\\s*(.+)$","i"),m=line.match(re);if(m?.[1])return clean(m[1])}}return ""};
 const dateRaw=val(["日期","用車日期","接送日期"])||match(t,[/\b(20\d{2}[\/-]\d{1,2}[\/-]\d{1,2})\b/,/\b(\d{1,2}[\/-]\d{1,2})\b/]);
 if(dateRaw){const nums=dateRaw.match(/\d+/g)||[];if(nums.length>=3)o.date=`${nums[0].padStart(4,"0")}-${nums[1].padStart(2,"0")}-${nums[2].padStart(2,"0")}`;else if(nums.length===2){const y=new Date().getFullYear();o.date=`${y}-${nums[0].padStart(2,"0")}-${nums[1].padStart(2,"0")}`}}
 const timeRaw=val(["時間","用車時間","接送時間","上車時間"])||match(t,[/\b((?:[01]?\d|2[0-3]):[0-5]\d)\b/]);
 const tm=timeRaw.match(/(?:上午|下午|早上|晚上)?\s*(\d{1,2})[:：](\d{2})/);
 if(tm){let h=Number(tm[1]);if(/下午|晚上/.test(timeRaw)&&h<12)h+=12;if(/上午|早上/.test(timeRaw)&&h===12)h=0;o.time=String(h).padStart(2,"0")+":"+tm[2]}
 o.name=clean(val(["客人姓名","乘客姓名","聯絡人","客人","姓名"]).replace(/\s*(?:電話|手機|聯絡電話)\s*[:：].*$/,""));
 o.phone=match(t,[/(?:電話|手機|聯絡電話)\s*[:：]?\s*(09\d{2}[- ]?\d{3}[- ]?\d{3})/i,/(09\d{2}[- ]?\d{3}[- ]?\d{3})/]).replace(/[- ]/g,"");
 o.pickup=val(["上車地點","上車地址","上車","接送地點","接人地點","出發地","起點","住址","地址"])||match(t,[/(?:接|從)\s*([^\n→>-]{5,}(?:市|縣)[^\n→>-]*)/]);
 o.dropoff=val(["下車地點","下車地址","下車","送達地點","送往","目的地","終點"])||match(t,[/(?:送|到)\s*([^\n]{4,}(?:機場|市|縣)[^\n]*)/]);
 const flightLine=val(["航班資訊","航班號碼","航班","班機號碼","班機","Flight"]);
 const flightSource=flightLine||t,flightCode=match(flightSource,[/\b((?:CI|BR|JX|CX|TR|SQ|JL|NH|MM|IT|VZ|FD|AK|KE|OZ|TG|VN|PR|5J|GK|TW|BX)[- ]?\d{2,4})\b/i,/\b([A-Z]{2,3}\d{2,4})\b/]);
 const flightTime=flightLine?match(flightLine,[/\b((?:[01]?\d|2[0-3]):[0-5]\d)\b/]):"";
 o.flight=flightCode+(flightTime?" / "+flightTime:"");
 o.passengers=match(t,[/(?:人數|乘客人數)\s*[:：]?\s*(\d+)/]);
 const luggageRaw=val(["托運行李","大行李","行李箱","行李"]);
 const parseLuggage=(s="")=>{const items=[];const re=/((?:32|30|28|26|24|22|20)\s*(?:吋|寸)|胖胖箱(?:\s*(?:32|30|28|26|24|22|20)\s*(?:吋|寸))?)\s*(?:(?:[xX×*]\s*)?(\d+)\s*件|[xX×*]\s*(\d+))?/g;let m;while((m=re.exec(s))){const size=m[1].replace(/寸/g,"吋").replace(/\s/g,"");const qty=m[2]||m[3]||"1";items.push(`${size} × ${qty}`)}return items.join("｜")};
 o.luggage=parseLuggage(luggageRaw||t);
 const carry=val(["手提行李","隨身行李","手提","隨身"]);o.carryOn=carry?match(carry,[/(\d+)\s*件?/]):match(t,[/(?:手提行李|隨身行李|手提|隨身)\s*[:：]?\s*(\d+)/]);
 o.vehicle=val(["車型","車種"]);
 o.amount=(val(["金額","車資","費用","價格"]).match(/[\d,]+/)||[""])[0].replace(/,/g,"");
 o.notes=val(["備註","其他"]);
 const airportText=[o.pickup,o.dropoff,t].filter(Boolean).join("\n").normalize("NFKC").replace(/\s+/g,"");
 if(/桃園(?:國際)?機場.*(?:第一航廈|第1航廈|一航廈|T1)|(?:第一航廈|第1航廈|一航廈|T1).*桃園(?:國際)?機場/i.test(airportText))o.airport="桃園T1";
 else if(/桃園(?:國際)?機場.*(?:第二航廈|第2航廈|二航廈|T2)|(?:第二航廈|第2航廈|二航廈|T2).*桃園(?:國際)?機場/i.test(airportText))o.airport="桃園T2";
 else if(/桃園(?:國際)?機場.*(?:第三航廈|第3航廈|三航廈|T3)|(?:第三航廈|第3航廈|三航廈|T3).*桃園(?:國際)?機場/i.test(airportText))o.airport="桃園T3";
 else if(/松山(?:機場)?/i.test(airportText))o.airport="松山機場";
 else if(/(?:清泉崗|台中)(?:機場)?/i.test(airportText))o.airport="清泉崗機場";
 else if(/台南(?:機場)?/i.test(airportText))o.airport="台南機場";
 else if(/(?:小港|高雄)(?:機場)?/i.test(airportText))o.airport="小港機場";
 const stops=t.match(/(?:第二(?:上|下)車|多點|加點|中途點|停靠點)\s*[:：]?\s*([^\n]+)/g);if(stops)o.extraStops=stops.map(x=>x.replace(/^[^:：]*[:：]?/,"").trim()).join("；");
 if(!o.pickup||!o.dropoff){const m=t.match(/([^\n]{4,})\s*(?:→|->|➡️?)\s*([^\n]{4,})/);if(m){o.pickup||=clean(m[1]);o.dropoff||=clean(m[2])}}
 const regionHit=(o.pickup||"").match(/(台北|新北|基隆|桃園|新竹|苗栗|台中|彰化|南投|雲林|嘉義|台南|高雄|屏東|宜蘭|花蓮|台東|澎湖|金門|連江)(?:市|縣)?/);if(regionHit)o.region=regionHit[1];
 return o;
}
export default function Home(){
 const [raw,setRaw]=useState(""),[data,setData]=useState(empty),[status,setStatus]=useState("未派"),[showStatusPicker,setShowStatusPicker]=useState(false),[trips,setTrips]=useState([]),[tab,setTab]=useState("總行程"),[editing,setEditing]=useState(null),[pasteMode,setPasteMode]=useState("車趟"),[showForm,setShowForm]=useState(false),[filters,setFilters]=useState({region:"",car:"",sort:"dateAsc"}),[drivers,setDrivers]=useState([]),[newDriver,setNewDriver]=useState({name:"",phone:"",car:"",license:"否",registration:"否",insurance:"否",blacklist:"否"}),[completedMonth,setCompletedMonth]=useState("");
 useEffect(()=>{try{setTrips(JSON.parse(localStorage.getItem("gdTrips")||"[]"));setDrivers(JSON.parse(localStorage.getItem("gdDrivers")||"[]"))}catch{}},[]);
 const persist=n=>{setTrips(n);localStorage.setItem("gdTrips",JSON.stringify(n))};
 const save=()=>{const previous=editing?trips.find(t=>t.id===editing):null;const completedAt=status==="已完成"?(previous?.completedAt||new Date().toISOString()):"";const item={...data,baseAmount:data.amount,amount:String(finalFare),surcharge:String(extraFare),status,completedAt,id:editing||Date.now()};const n=editing?trips.map(t=>t.id===editing?item:t):[item,...trips];persist(n);setRaw("");setData(empty);setEditing(null);setShowForm(false)};
 const edit=t=>{setData({...empty,...t});setStatus(t.status);setEditing(t.id);setShowForm(true);window.scrollTo({top:0,behavior:"smooth"})};
 const remove=id=>{if(confirm("確定刪除這筆車趟？"))persist(trips.filter(t=>t.id!==id))};
 const mapUrl=a=>"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(a||"");
 const saveDrivers=n=>{setDrivers(n);localStorage.setItem("gdDrivers",JSON.stringify(n))};
 const addDriver=()=>{if(!newDriver.name.trim())return;saveDrivers([...drivers,{...newDriver,id:Date.now()}]);setNewDriver({name:"",phone:"",car:"",license:"否",registration:"否",insurance:"否",blacklist:"否"})};
 const pickDriver=e=>{const d=drivers.find(x=>String(x.id)===e.target.value);if(d)setData({...data,driver:d.name,driverPhone:d.phone,vehicle:data.vehicle||d.car})};
 const extraFare=(()=>{const km=Number(data.extraKm)||0;let d=km>40?700+Math.ceil((km-40)/10)*100:km>=31?700:km>=21?600:km>=12?400:km>=9?300:km>=5?200:km>0?100:0;return d+(data.crossCounty==="是"?300:0)+(Number(data.childSeat)||0)*100+(Number(data.booster)||0)*100})();
 const finalFare=(Number(String(data.amount||0).replace(/,/g,""))||0)+extraFare;
 const total=trips.reduce((s,t)=>s+(Number(String(t.amount||0).replace(/,/g,""))||0),0);
 const unpaid=trips.filter(t=>t.payment!=="已收").reduce((s,t)=>s+(Number(String(t.amount||0).replace(/,/g,""))||0),0);
 const pendingReturn=trips.filter(t=>t.returnMoney!=="已回金").reduce((s,t)=>s+(Number(String(t.amount||0).replace(/,/g,""))||0),0);
 const visible=(tab==="總行程"?trips:trips.filter(x=>x.status===tab)).filter(x=>(!filters.region||x.region===filters.region)&&(!filters.car||x.carClass===filters.car)).sort((a,b)=>{if(filters.sort==="amountDesc")return (Number(b.amount)||0)-(Number(a.amount)||0);if(filters.sort==="amountAsc")return (Number(a.amount)||0)-(Number(b.amount)||0);const A=(a.date||"")+" "+(a.time||""),B=(b.date||"")+" "+(b.time||"");return filters.sort==="dateDesc"?B.localeCompare(A):A.localeCompare(B)});
 const monthly=trips.reduce((m,t)=>{const k=(t.date||"未填日期").slice(0,7);m[k]=(m[k]||0)+(Number(t.amount)||0);return m},{});
 const completedTrips=trips.filter(t=>t.status==="已完成");
 const completedMonths=[...new Set(completedTrips.map(t=>(t.date||"未填日期").slice(0,7)))].sort().reverse();
 const completedVisible=completedTrips.filter(t=>!completedMonth||(t.date||"未填日期").slice(0,7)===completedMonth).sort((a,b)=>((b.date||"")+" "+(b.time||"")).localeCompare((a.date||"")+" "+(a.time||"")));
 const field=(k,l,type="text")=><label style={{display:"grid",gap:5}}><b>{l}</b><input type={type} value={data[k]} onChange={e=>setData({...data,[k]:e.target.value})} style={inp}/></label>;
 return <main style={{maxWidth:980,margin:"20px auto",padding:16,fontFamily:"system-ui"}}>
  <h1>GD 車趟管理 <small style={{fontSize:14}}>v2.0</small></h1>
  {showStatusPicker&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.45)",zIndex:99,display:"grid",placeItems:"center",padding:20}}><div style={{background:"#fff",borderRadius:16,padding:20,width:"min(520px,100%)",boxShadow:"0 12px 40px rgba(0,0,0,.25)"}}><h2 style={{marginTop:0}}>資料解析完成</h2><p>請選擇這筆車趟要歸到哪個狀態：</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{["未派","已派","已接","已完成"].map(x=><button key={x} onClick={()=>{setStatus(x);setShowStatusPicker(false)}} style={{...btn(status===x),padding:16,fontSize:18}}>{x}</button>)}</div><button onClick={()=>setShowStatusPicker(false)} style={{...btn(false),width:"100%",marginTop:10}}>稍後再選</button></div></div>}
  <div style={{background:"#fff",padding:"8px 0",borderBottom:"1px solid #eee",marginBottom:12}}><nav style={{display:"flex",gap:8,overflowX:"auto",whiteSpace:"nowrap"}}>{["總行程","已接","已派","未派","已完成"].map(x=><button onClick={()=>setTab(x)} style={btn(tab===x)}>{x} ({x==="總行程"?trips.length:trips.filter(t=>t.status===x).length})</button>)}</nav></div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:12}}><button onClick={()=>{setShowForm(!showForm);setPasteMode("車趟")}} style={{...btn(true),fontSize:17,padding:14}}>＋ 新增車趟</button><button onClick={()=>{setShowForm(true);setPasteMode("司機")}} style={{...btn(false),fontSize:17,padding:14}}>＋ 新增司機</button></div>
  {showForm&&<><section style={card}><h2>智慧貼單 v2</h2><div style={{display:"flex",gap:8,marginBottom:8}}>{["車趟","司機"].map(x=><button key={x} onClick={()=>setPasteMode(x)} style={btn(pasteMode===x)}>{x}資料</button>)}</div><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder="貼上 LINE／客戶完整車趟資料…" style={{...inp,width:"100%",height:150}}/><button onClick={()=>{if(pasteMode==="車趟"){setData({...data,...parseTrip(raw)});setShowStatusPicker(true)}else setNewDriver({...newDriver,...parseDriver(raw)})}} style={{...btn(true),marginTop:10}}>自動分析填入</button><div style={{fontSize:13,marginTop:8}}>可辨識：完整地址、航班代碼、人數、多尺寸行李（例如 28吋2件＋胖胖箱1件）、手提行李件數，以及司機姓名／電話／車牌／三證。</div></section>
  <section style={card}><h2>新增／確認車趟</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}>
   {field("date","日期","date")}{field("time","時間","time")}
   <label><b>服務類型</b><select value={data.service} onChange={e=>setData({...data,service:e.target.value})} style={inp}>{["機場接送","接機","送機","包車旅遊","登山接駁","單車補給"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><b>地區</b><select value={data.region} onChange={e=>setData({...data,region:e.target.value})} style={inp}><option value="">請選擇</option>{["台北","新北","基隆","桃園","新竹","苗栗","台中","彰化","南投","雲林","嘉義","台南","高雄","屏東","宜蘭","花蓮","台東","澎湖","金門","連江"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><b>固定航點</b><select value={data.airport} onChange={e=>setData({...data,airport:e.target.value})} style={inp}><option value="">請選擇</option>{["桃園T1","桃園T2","桃園T3","松山機場","清泉崗機場","台南機場","小港機場"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><b>車型分類</b><select value={data.carClass} onChange={e=>setData({...data,carClass:e.target.value})} style={inp}><option value="">請選擇</option>{["轎車","小車","大車","正七","假七","九人座"].map(x=><option key={x}>{x}</option>)}</select></label>{field("name","客人姓名")}{field("phone","電話")}{field("pickup","上車完整住址")}{field("dropoff","下車完整住址")}{field("extraStops","多點上下車／中途停靠")}{field("extraKm","多點額外距離 KM","number")}
   <label><b>跨縣市</b><select value={data.crossCounty} onChange={e=>setData({...data,crossCounty:e.target.value})} style={inp}><option>否</option><option>是</option></select></label>{field("flight","航班")}{field("passengers","人數","number")}
   <label><b>行李（可多尺寸）</b><input list="luggage-sizes" value={data.luggage} onChange={e=>setData({...data,luggage:e.target.value})} placeholder="例如：28吋 × 2｜胖胖箱 × 1" style={inp}/><datalist id="luggage-sizes">{sizes.map(x=><option key={x} value={x}/>)}</datalist></label>
   {field("carryOn","手提行李（件數）","number")}{field("vehicle","車型")}{field("amount","金額","number")}
   <label><b>派單司機</b><select onChange={pickDriver} style={inp}><option value="">從司機資料庫選擇</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.name}｜{d.car||"未填車型"}</option>)}</select></label>
   {field("driver","司機姓名")}{field("driverPhone","司機電話")}{field("returnAccount","回金帳號")}
   <label><b>兒童安全座椅</b><select value={data.childSeat} onChange={e=>setData({...data,childSeat:e.target.value})} style={inp}>{["0","1","2","3"].map(x=><option key={x} value={x}>{x} 個</option>)}</select></label>
   <label><b>增高墊</b><select value={data.booster} onChange={e=>setData({...data,booster:e.target.value})} style={inp}>{["0","1","2","3"].map(x=><option key={x} value={x}>{x} 個</option>)}</select></label>
   <label><b>收款狀態</b><select value={data.payment} onChange={e=>setData({...data,payment:e.target.value})} style={inp}><option>未收</option><option>已收</option><option>現金當場收款</option></select></label>
   <label><b>回金狀態</b><select value={data.returnMoney} onChange={e=>setData({...data,returnMoney:e.target.value})} style={inp}><option>待回金</option><option>已回金</option></select></label>{field("notes","備註")}
  </div><div style={{marginTop:14,padding:12,border:"1px dashed #aaa",borderRadius:8}}><b>自動加價：$ {extraFare.toLocaleString()}</b>　基本車資：$ {(Number(data.amount)||0).toLocaleString()}　<strong>預估總車資：$ {finalFare.toLocaleString()}</strong><div style={{fontSize:13,marginTop:5}}>跨縣市 +300｜安全座椅/增高墊每個 +100｜多點距離依級距自動加價</div></div>
  <div style={{display:"flex",gap:8,marginTop:14,flexWrap:"wrap"}}>{["已派","未派","已接","已完成"].map(x=><button onClick={()=>setStatus(x)} style={btn(status===x)}>{x}</button>)}<button onClick={save} style={{...btn(true),marginLeft:"auto"}}>{editing?"更新車趟":"儲存車趟"}</button></div></section>
  </>}
  <section style={card}><h2>首頁儀表板</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10}}>{[["總行程",trips.length],["未派",trips.filter(t=>t.status==="未派").length],["已派",trips.filter(t=>t.status==="已派").length],["已接",trips.filter(t=>t.status==="已接").length],["已完成",trips.filter(t=>t.status==="已完成").length],["未收款",trips.filter(t=>t.payment!=="已收"&&t.payment!=="現金當場收款").length],["待回金",trips.filter(t=>t.returnMoney!=="已回金").length]].map(([l,v])=><div key={l} style={{padding:12,border:"1px solid #ddd",borderRadius:10}}><div>{l}</div><b style={{fontSize:24}}>{v}</b></div>)}</div></section>
  <section style={card}><h2>待處理提醒</h2>{trips.filter(t=>t.status==="未派"||t.payment==="未收"||t.returnMoney!=="已回金").slice(0,8).map(t=><div key={t.id} style={{padding:"6px 0",borderTop:"1px solid #eee"}}>⚠️ {t.date} {t.time} {t.name||"未填姓名"}｜{t.status}｜收款:{t.payment||"未收"}｜回金:{t.returnMoney||"待回金"} {t.returnAccount?"｜帳號:"+t.returnAccount:""}</div>)}</section>
  <section style={card}><h2>篩選／排序</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8}}><select value={filters.region} onChange={e=>setFilters({...filters,region:e.target.value})} style={inp}><option value="">全部地區</option>{["台北","新北","基隆","桃園","新竹","苗栗","台中","彰化","南投","雲林","嘉義","台南","高雄","屏東","宜蘭","花蓮","台東","澎湖","金門","連江"].map(x=><option key={x}>{x}</option>)}</select><select value={filters.car} onChange={e=>setFilters({...filters,car:e.target.value})} style={inp}><option value="">全部車型</option>{["轎車","小車","大車","正七","假七","九人座"].map(x=><option key={x}>{x}</option>)}</select><select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})} style={inp}><option value="dateAsc">日期時間：近→遠</option><option value="dateDesc">日期時間：遠→近</option><option value="amountDesc">金額：高→低</option><option value="amountAsc">金額：低→高</option></select></div></section>
  <section style={card}><h2>帳務摘要</h2><div style={{display:"flex",gap:20,flexWrap:"wrap"}}><b>應收：$ {total.toLocaleString()}</b><b>未收：$ {unpaid.toLocaleString()}</b><b>待轉回金：$ {pendingReturn.toLocaleString()}</b></div><div style={{marginTop:12}}><b>月收入統計：</b>{Object.entries(monthly).sort().reverse().map(([m,v])=><span key={m} style={{display:"inline-block",margin:"6px 12px 0 0"}}>{m}：$ {v.toLocaleString()}</span>)}</div></section>
  <section style={card}><h2>{tab}</h2>{visible.length===0?<p>目前沒有資料</p>:visible.map(t=><div key={t.id} style={{border:"1px solid #ddd",borderRadius:12,padding:12,marginBottom:10,boxShadow:"0 1px 3px rgba(0,0,0,.06)"}}><b>{t.date} {t.time}｜{t.name||"未填姓名"}｜{t.status}</b><div><a href={mapUrl(t.pickup)} target="_blank">📍 {t.pickup||"未填上車地"}</a> → <a href={mapUrl(t.dropoff)} target="_blank">📍 {t.dropoff||"未填下車地"}</a></div><div>類型：{t.service||"-"}　地區：{t.region||"-"}　航點：{t.airport||"-"}　車型：{t.carClass||t.vehicle||"-"}<br/>航班：{t.flight||"-"}　多點：{t.extraStops||"-"}<br/>行李：{t.luggage||"-"}　手提：{t.carryOn||"-"}　安全座椅：{t.childSeat||0}　增高墊：{t.booster||0}　跨縣市：{t.crossCounty||"否"}　多點KM：{t.extraKm||0}　基本：{t.baseAmount||t.amount||"-"}　加價：{t.surcharge||0}　<b>總額：{t.amount||"-"}</b>　收款：{t.payment||"未收"}　回金：{t.returnMoney||"待回金"}　回金帳號：{t.returnAccount||"-"}</div><div>司機：{t.driver||"未派"} {t.driverPhone||""}</div><div style={{display:"flex",gap:8,marginTop:8}}><button onClick={()=>edit(t)} style={btn(false)}>編輯</button><button onClick={()=>remove(t.id)} style={btn(false)}>刪除</button></div></div>)}</section>
  <section style={card}><h2>每月已完成清單</h2><p style={{fontSize:13,color:"#666"}}>完成車趟會永久留在這裡，可依月份回查客人、司機、地址、金額、收款、回金與備註。</p><select value={completedMonth} onChange={e=>setCompletedMonth(e.target.value)} style={{...inp,marginBottom:10}}><option value="">全部月份（{completedTrips.length} 趟）</option>{completedMonths.map(m=><option key={m} value={m}>{m}（{completedTrips.filter(t=>(t.date||"").slice(0,7)===m).length} 趟）</option>)}</select>{completedVisible.map(t=><div key={t.id} style={{padding:12,border:"1px solid #ddd",borderRadius:10,marginBottom:8}}><b>{t.date} {t.time}｜{t.name||"未填姓名"}</b><div>📍 {t.pickup||"-"} → {t.dropoff||"-"}</div><div>電話：{t.phone||"-"}｜航班：{t.flight||"-"}｜司機：{t.driver||"未派"}</div><div>金額：$ {Number(t.amount||0).toLocaleString()}｜收款：{t.payment||"未收"}｜回金：{t.returnMoney||"待回金"}</div><div>備註：{t.notes||"-"}</div><div style={{fontSize:12,color:"#666"}}>完成時間：{t.completedAt?new Date(t.completedAt).toLocaleString("zh-TW"):"舊資料未記錄"}</div><button onClick={()=>edit(t)} style={{...btn(false),marginTop:6}}>查看／追查／編輯原車趟</button></div>)}{completedVisible.length===0&&<p>目前沒有已完成車趟。</p>}</section>  <section style={card}><h2>司機資料庫</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8}}><input placeholder="司機姓名" value={newDriver.name} onChange={e=>setNewDriver({...newDriver,name:e.target.value})} style={inp}/><input placeholder="電話" value={newDriver.phone} onChange={e=>setNewDriver({...newDriver,phone:e.target.value})} style={inp}/><input placeholder="車型／車牌" value={newDriver.car} onChange={e=>setNewDriver({...newDriver,car:e.target.value})} style={inp}/>{[["license","駕照"],["registration","行照"],["insurance","保險"],["blacklist","黑名單"]].map(([k,l])=><label key={k}><b>{l}</b><select value={newDriver[k]} onChange={e=>setNewDriver({...newDriver,[k]:e.target.value})} style={inp}><option>否</option><option>是</option></select></label>)}<button onClick={addDriver} style={btn(true)}>新增司機</button></div>{drivers.map(d=><div key={d.id} style={{padding:"8px 0",borderTop:"1px solid #eee"}}>{d.blacklist==="是"?"⚠️ 黑名單｜":""}{d.name}｜{d.phone||"-"}｜{d.car||"-"}｜三證：駕照{d.license==="是"?"✓":"✗"} 行照{d.registration==="是"?"✓":"✗"} 保險{d.insurance==="是"?"✓":"✗"} <button onClick={()=>saveDrivers(drivers.filter(x=>x.id!==d.id))}>刪除</button></div>)}</section>

 </main>
}
const inp={padding:12,fontSize:16,border:"1px solid #bbb",borderRadius:8,boxSizing:"border-box",width:"100%"};
const card={padding:14,border:"1px solid #ddd",borderRadius:14,marginBottom:14,background:"#fff"};
const btn=a=>({padding:"11px 16px",borderRadius:8,border:"1px solid #aaa",fontSize:15,fontWeight:a?700:400,cursor:"pointer"});
