import {NextResponse} from "next/server";
import {getDb,ensureSchema} from "../../../lib/db";
import {auth} from "../../../lib/auth/server";
async function userFrom(){const r=await auth.getSession();return r?.user||r?.data?.user||null}
const ROOT_OWNERS=new Set(["delta198073@icloud.com","judehu100427@icloud.com"]);
async function roleFor(sql,u){const email=String(u?.email||"").trim().toLowerCase();const configured=(process.env.GD_OWNER_EMAIL||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);if(ROOT_OWNERS.has(email)||configured.includes(email))return "owner";const rows=await sql.query("SELECT role,status,pro_expires_at FROM gd_access_control WHERE owner_id=$1",[u.id]);const a=rows[0];if(!a||a.status==="suspended")return "free";if(a.role==="pro"&&a.pro_expires_at&&new Date(a.pro_expires_at)<=new Date())return "free";return a.role||"free"}
export async function GET(){
 const u=await userFrom();if(!u?.id)return NextResponse.json({error:"unauthorized"},{status:401});
 const sql=getDb();if(!sql)return NextResponse.json({error:"database_not_configured"},{status:503});
 try{await ensureSchema(sql);const role=await roleFor(sql,u);if(role!=="owner")return NextResponse.json({error:"owner_only"},{status:403});const rows=await sql.query("SELECT owner_id,email,role,pricing_enabled,status,pro_expires_at,updated_at FROM gd_access_control ORDER BY updated_at DESC");return NextResponse.json({role,users:rows})}catch(e){console.error("GD access GET failed",e);return NextResponse.json({error:"database_unavailable"},{status:503})}
}
export async function PUT(req){
 const u=await userFrom();if(!u?.id)return NextResponse.json({error:"unauthorized"},{status:401});
 const sql=getDb();if(!sql)return NextResponse.json({error:"database_not_configured"},{status:503});
 try{await ensureSchema(sql);const role=await roleFor(sql,u);if(role!=="owner")return NextResponse.json({error:"owner_only"},{status:403});const b=await req.json();const target=String(b.ownerId||"").trim(),targetEmail=String(b.email||"").trim().toLowerCase();if(ROOT_OWNERS.has(targetEmail))return NextResponse.json({error:"protected_owner",message:"Root Owner cannot be changed."},{status:403});const nextRole=["admin","pro","free"].includes(b.role)?b.role:null,status=["active","suspended"].includes(b.status)?b.status:"active",expires=b.proExpiresAt?new Date(b.proExpiresAt):null;if(!target||!nextRole||expires&&Number.isNaN(expires.getTime()))return NextResponse.json({error:"invalid_request"},{status:400});await sql.query("INSERT INTO gd_access_control(owner_id,email,role,pricing_enabled,status,pro_expires_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,NOW()) ON CONFLICT(owner_id) DO UPDATE SET email=EXCLUDED.email,role=EXCLUDED.role,pricing_enabled=EXCLUDED.pricing_enabled,status=EXCLUDED.status,pro_expires_at=EXCLUDED.pro_expires_at,updated_at=NOW()",[target,targetEmail,nextRole,status==="active"&&(nextRole==="admin"||nextRole==="pro")&&(nextRole!=="pro"||!expires||expires>new Date()),status,nextRole==="pro"&&expires?expires.toISOString():null]);return NextResponse.json({ok:true,role:nextRole})}catch(e){console.error("GD access PUT failed",e);return NextResponse.json({error:"update_failed"},{status:500})}
}